### ISSUE TITLE
能否增加自动推送的功能

### ISSUE THREAD

**Issue by 362227** [iszhouhua/cookie-push#1]
能否增加自动推送的功能？比如每天一次，每12小时一次。因为有些网站cookie会时不时变化

**Comment by 362227** [comment]
发现旧版就支持，不过请求方法不支持GET，能否添加

编辑：旧版的自动推送好像没有用

**Comment by wedcf120** [comment]
希望可以出一个自动推送功能，以应对一些cookie有效期过短的网站
