### ISSUE TITLE
自动推送的功能好像无效

### ISSUE THREAD

**Issue by 362227** [iszhouhua/cookie-push#2]
cookie确定时时刻刻在变化，所有的cookie段都监视了，就是保存配置那一刻会推送，然后再也不会推送了，手动推送也正常

**Comment by iszhouhua** [comment]
检查一下相关配置，是否已经达到了最短推送间隔，cookie是否发生了变化。配置没问题就自行打印日志日志看是哪一步有问题

**Comment by iszhouhua** [comment]
> cookie确定时时刻刻在变化，所有的cookie段都监视了，就是保存配置那一刻会推送，然后再也不会推送了，手动推送也正常

检查一下相关配置，是否已经达到了最短推送间隔，cookie是否发生了变化。配置没问题就自行打印日志日志看是哪一步有问题。每个网站的情况略有不同，我自己测试的是没问题的。

**Comment by 362227** [comment]
能否新增自动推送频率设置，不管有没有变化都会推送，设置时间间隔就可以

**Comment by 362227** [comment]
确定是浏览器问题，怀疑和某扩展冲突了
